config/routes.rb
Rails.application.routes.draw do
  root 'pages#front'
  get 'my_games', to: 'pages#my_games'
  resources :games
  resources :categories do
    resources :answers, only: [:create]
  end
  resources :answers, only: [:destroy]
  get '/game_play/:id', to: 'games#game_play', as: :game_play
  get '/search_games', to: 'games#search'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/answer.rb
class Answer < ActiveRecord::Base  
  validates_presence_of :content
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  belongs_to :game
  has_many :answers, :dependent => :delete_all
  validates :answers, :length => { :maximum => 5 }
  
  def complete?
    answers.count == 5
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates_presence_of :name
  has_many :categories, :dependent => :delete_all
  belongs_to :user
  
  def complete?
    categories.all? { |category| category.complete? }
  end
  
  def percent_complete
    sum = 0
    categories.each do |category|
      sum += category.answers.count
    end
    ((sum / 30.00) * 100).to_s + "%"
  end
end

app/models/search.rb
class Search
  def self.search_games(search_term)
    return [] if search_term.empty?
    Game.where("name Like ?", "%#{search_term}%").where("plays > ?", 0).order("plays DESC")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_user
  
  def create
    @category = Category.find(params[:category_id])
    @answer = Answer.new(answer_params)
    @answer.category = @category
    @game = @category.game
    
    if @answer.valid?
      if @answer.category.answers.count < 5
        @answer.save
        redirect_to @game
      else
        flash.now[:danger] = "You cannot create more than five answers per category"
        render 'games/show'
      end
    else
      redirect_to @game
    end
  end
  
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to @answer.category.game
  end
  
  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def access_denied
    flash[:danger] = "You must be logged in to do that"
    redirect_to root_path
  end
  
  def require_user
    access_denied unless logged_in?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_user
  before_action :find_game, only: [:show, :destroy, :edit, :update]
  before_action :require_creator, only: [:show, :destroy, :edit, :update]
  
  def index
    @games = Game.where("plays > ?", 0).order("plays DESC")
  end
  
  def new
    @game = Game.new
  end
  
  def show
  end
  
  def create
    @game = Game.new(game_params)
    
    @category_one = Category.new(name: params[:game][:category][0], game: @game)
    @category_two = Category.new(name: params[:game][:category][1], game: @game)
    @category_three = Category.new(name: params[:game][:category][2], game: @game)
    @category_four = Category.new(name: params[:game][:category][3], game: @game)
    @category_five = Category.new(name: params[:game][:category][4], game: @game)
    @category_six = Category.new(name: params[:game][:category][5], game: @game)
    
    if @game.valid? && @category_one.valid? && @category_two.valid? && 
       @category_three.valid? && @category_four.valid? && @category_five.valid? && @category_six.valid?
      
      @game.user_id = current_user.id
      
      @game.save
      @category_one.save
      @category_two.save
      @category_three.save
      @category_four.save
      @category_five.save
      @category_six.save
      
      redirect_to @game
    else
      flash.now[:danger] = "You must enter a game name and six categories"
      render :new
    end
  end
  
  def edit
  end
  
  def update
    @category_one = @game.categories[0]
    @category_two = @game.categories[1]
    @category_three = @game.categories[2]
    @category_four = @game.categories[3]
    @category_five = @game.categories[4]
    @category_six = @game.categories[5]
    
    @category_one.name = params[:game][:category][0]
    @category_two.name = params[:game][:category][1]
    @category_three.name = params[:game][:category][2]
    @category_four.name = params[:game][:category][3]
    @category_five.name = params[:game][:category][4]
    @category_six.name = params[:game][:category][5]
    
    if @game.valid? && @category_one.valid? && @category_two.valid? && 
       @category_three.valid? && @category_four.valid? && @category_five.valid? && @category_six.valid?
      
      @game.save
      @category_one.save
      @category_two.save
      @category_three.save
      @category_four.save
      @category_five.save
      @category_six.save
      
      redirect_to @game
    else
      flash[:danger] = "The name and category field must all be filled in"
      redirect_to edit_game_path(@game)
    end
  end
  
  def destroy
    @game.categories.each do |category|
      category.destroy
    end
    @game.destroy
    redirect_to my_games_path
  end
  
  def game_play
    @game = Game.find(params[:id])
    if @game.complete?
      @game.increment!(:plays)
    else
      flash[:danger] = "That game is not ready to play."
      if @game.user.id == current_user.id
        flash[:danger] += " Make sure each category has 5 answers."
        redirect_to @game
      else
        redirect_to root_path
      end
    end
  end
  
  def search
    @games = Search.search_games(params[:search_term])
  end
  
  private
  def game_params
    params.require(:game).permit(:name)
  end
  
  def find_game
    @game = Game.find(params[:id])
  end
  
  def require_creator
    if @game.user.id != current_user.id
      flash[:danger] = "That is not your game to edit."
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_user, only: [:my_games]
  
  def front
    redirect_to my_games_path if logged_in?
  end
  
  def my_games
    @games = current_user.games
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  private
  def session_params
    params.permit(:uid, :provider)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/edit.html.erb
<h1>Edit Game</h1>
<br>
<h3>Name of Game:</h3>
<br>
<%= bootstrap_form_for @game do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="well">
        <%= f.text_field :name %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <h3>Categories:</h3>
      <br>
    </div>
  </div>
  <div class="row">
    <% @game.categories.each_with_index do |category, i| %>
      <div class="col-sm-2">
        <div class="well">
          <label for="category_<%= i + 1 %>"><%= "Category #{i + 1}" %></label>
          <%= text_field_tag "game[category][]", category.name, class: "form-control", id: "category_#{i + 1}" %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

app/views/games/game_play.html.erb
<br>
<h1 class="text-center"><%= @game.name %></h1>

<% @game.categories.each do |category| %>
  <div class="col-sm-2">
    <h1 class="text-center"><%= category.name %></h1>
    <% category.answers.each_with_index do |answer, index| %>
      <div class="well card light-blue">
        <h1 class="text-center points"><%= (index + 1) * 100 %></h1>
        <h2 class="text-center answer"><%= answer.content %></h2>
      </div>
    <% end %>
  </div>
<% end %>

<script>
  $('.card').on("click", function() {
    $(this).children(".points").hide();
    $(this).children(".answer").fadeIn(2000);
  });
</script>

app/views/games/index.html.erb
<h2>Most Popular Games</h2>
<br>
<div class="row">
  <% @games.each do |game| %>
    <div class="col-sm-3">
      <div class="well">
        <h3><%= game.name %></h3>
        <p>Plays: <%= game.plays %></p>
        <%= link_to "play", game_play_url(game) %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<h1>Create New Game</h1>
<br>
<h3>Name Your Game:</h3>
<br>
<%= bootstrap_form_for @game do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="well">
        <%= f.text_field :name %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <h3>Add Categories:</h3>
      <br>
    </div>
  </div>
  <div class="row">
    <% 6.times do |i| %>
      <div class="col-sm-2">
        <div class="well">
          <label for="category_<%= i + 1 %>"><%= "Category #{i + 1}" %></label>
          <%= text_field_tag "game[category][]", "", class: "form-control", id: "category_#{i + 1}" %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>

app/views/games/search.html.erb
<h2>Search Results:</h2>
<br>
<div class="row">
  <% @games.each do |game| %>
    <div class="col-sm-3">
      <div class="well">
        <h3><%= game.name %></h3>
        <p>Plays: <%= game.plays %></p>
        <%= link_to "play", game_play_url(game) %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<h1 class="text-center"><%= @game.name %> <%= link_to "Play Game", game_play_path(@game), class: "btn btn-success", style: "margin-bottom: 5px;" if @game.complete? %></h1>
<br>
<div class="text-center">
  <%= link_to "Edit Name and Categories", edit_game_path(@game), class: "btn btn-success" %>
</div>
<br>
<br>
<div class="row">
  <% @game.categories.each do |category| %>
  
    <div class="col-sm-2">
      <div class="well">
        <h3 class="text-center"><%= category.name %></h3>
      </div>
      <%= bootstrap_form_for [category, category.answers.build] do |answer| %>
        <%= answer.text_field :content, label: "Add Answer" %>
        <%= answer.submit "Add Answer", class: "btn btn-success" %>
      <% end %>
      <h3>Answers</h3>
      
      <% category.answers.each do |answer| %>
        <% if !answer.new_record? %> 
          <div class="well">
            <h5><%= answer.content %></h5>
            <%= link_to "Delete", answer_path(answer), method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        <% end %>
      <% end %>
      
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= link_to "Save Game", root_path, class: "btn btn-success" %>
    <br><br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jeopardy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body “data-no-turbolink”>
    <div class="container">
      <%= render 'shared/header' %>
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/front.html.erb
<div class="jumbotron text-center">
  <h1 class="text-center">This Is Jeopardy!</h1>
  <br>
  <p class="text-center">Create your own Jeopardy smart board game to play with your kids and share with other teachers.</p>
  <br>
  <div id="user-widget">
    <% if current_user %>
      Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out", class: "btn btn-default" %>
    <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "btn btn-default facebook-link" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 text-center">
    <div class="well">
      <h2>Make Your Game</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
  <div class="col-sm-4 text-center">
    <div class="well">
      <h2>Play It</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
  <div class="col-sm-4 text-center">
    <div class="well">
      <h2>Share It</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
</div>

app/views/pages/my_games.html.erb
<h2>Welcome, <%= current_user.name %></h2>
<br>
<div class="row">
  <% current_user.games.each do |game| %>
    <div class="col-sm-3">
      <div class="well">
        <h3><%= game.name %></h3>
        <h4><%= game.complete? ? "Ready to Play" : "Work in Progress" %></h4>
        <div class="progress progress-striped">
          <div class="progress-bar progress-bar-success" style="width: <%= game.percent_complete %>"></div>
        </div>
        <%= link_to game, class: "btn btn-danger btn-game", method: :delete, :data => {:confirm => 'Are you sure?'} do %>
          delete <i class="glyphicon glyphicon-trash"></i>
        <% end %>
        <%= link_to game, class: "btn btn-warning btn-game" do %>
          edit <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <% if game.complete? %>
          <%= link_to game_play_url(game), class: "btn btn-success btn-game" do %>
            play <i class="glyphicon glyphicon-expand"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New Game", new_game_path, class: "btn btn-success" %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Jeopardy", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
          <li><%= link_to "New Game", new_game_path %></li>
          <li><%= link_to "All Games", games_path %></li>
          <li><%= link_to "My Games", root_path %></li>
        <% else %>
          <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
        <% end %>
      </ul>
      <% if logged_in? %>
        <%= form_tag search_games_path, method: :get, :class => "navbar-form navbar-right" do %>
          <div class="form-group">
            <%= text_field_tag :search_term, "", class: "form-control" %>
          </div>
          <%= submit_tag "Seach", class: "btn btn-default" %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>">
    <div id="flash_<%= name %>"><%= msg %></div>
  </div>
<% end %>